### ISSUE TITLE
[色板] 颜色深浅与序号顺序

### ISSUE THREAD

**Issue by svchord** [Tencent/tdesign-vue-next-starter#304]
### tdesign-vue-next-starter 版本

0.5.0

### 重现步骤

`src/style/theme`目录下的几个色板文件有点问题

```less
:root[theme-color='orange'] {
  --td-brand-color: #ed7b2f;
  --td-brand-color-1: #fce5d7;
  --td-brand-color-2: #f8cdaf;
  --td-brand-color-3: #f4b285;
  --td-brand-color-4: #f19659;
  --td-brand-color-5: #ed7b2f;
  --td-brand-color-6: #e75510;
  --td-brand-color-7: #f19659;
  --td-brand-color-8: #ed7b2f;
  --td-brand-color-9: #e75510;
  --td-brand-color-10: #7f0a02;
  --td-brand-color: #ed7b2f;
}
```

颜色深浅与序号顺序不一致，其他颜色中有的也有这种问题

### 期望结果

色板修改好

### 实际结果

![image](https://user-images.githubusercontent.com/61345763/189493289-ffa45e78-9513-43c6-9579-620eda9bd2ee.png)
